<div id="dashboard">
    <div class="dashboard-item">
        <div id="staff_image"><a href="<?php echo $this->baseUrl() . '/admin/staff/add'; ?>"> </a></div>
    </div>
       <div class="dashboard-item">
        <div id="candidate_image"><a href="<?php echo $this->baseUrl() . '/admin/candidate/add'; ?>"> </a></div>
    </div>
     <div class="dashboard-item">
        <div id="agent_image"><a href="<?php echo $this->baseUrl() . '/admin/agent/add'; ?>"> </a></div>
    </div>
    <div class="dashboard-item">
        <div id="stamping_image"><a href="<?php echo $this->baseUrl() . '/admin/stamping/add'; ?>"> </a></div>
    </div>
    <div class="dashboard-item">
        <div id="orientation_image"><a href="<?php echo $this->baseUrl() . '/admin/orientation/add'; ?>"> </a></div>
    </div>
    <div class="dashboard-item">
        <div id="medical_image"><a href="<?php echo $this->baseUrl() . '/admin/medical/add'; ?>"> </a></div></div>
    <div class="dashboard-item">
        <div id="company_image"><a href="<?php echo $this->baseUrl() . '/admin/company/add'; ?>"></a></div></div>
    <div class="dashboard-item">
        <div id="category_image"><a href="<?php echo $this->baseUrl() . '/admin/category/add'; ?>"></a></div></div>
</div>