<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . "/destiny/admin/css/table.css"); ?>
<table id="table" >

    <tr>
        <th> Candidate Name    </th>
        <th> MOFA No.    </th>
        <th> Gamca No. </th>
        <th> Medical Center </th>
        <th> Company Name </th>
        <th> ID No. </th>
        <th> Visa No. </th>
        <th> Edit </th>
        <th> Delete</th>
    </tr>
    <?php foreach ($this->result as $result): ?>

        <tr>
            <td><?php echo $result['candidate_name']; ?></td>
            <td><?php echo $result['mofa_no']; ?></td>
            <td><?php echo $result['gamca_no']; ?></td>
            <td><?php echo $result['medical_center']; ?></td>
            <td><?php echo $result['company_name']; ?></td>
            <td><?php echo $result['id_number']; ?></td>
            <td><?php echo $result['visa_no']; ?></td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'medical', 'action' => 'edit', 'id' => $result['medical_id'])); ?>">Edit </a>
            </td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'medical', 'action' => 'delete', 'id' => $result['medical_id'])); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
