<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php $form = $this->form->getElements(); ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . "/destiny/admin/css/bootstrap.css"); ?>
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->baseUrl() . '/destiny/admin/css/form.css')
                ->prependStylesheet($this->baseUrl() . '/destiny/admin/css/style.css')
                ->prependStylesheet($this->baseUrl() . '/destiny/admin/css/bootstrap.min.css')
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()->appendFile($this->baseUrl() . '/common/js/jquery-1.7.2.min.js');
        ?>
    </head>

    <div class="form-wrap">
        <form action="" method="post">
            <fieldset class="span11">
                <legend><h3>Add Orientation Report</h3></legend>
                <div id="agent_span">
                    <div class="span4"><?php echo $form["orientation_id"]; ?></div>
                </div>
                <div class="span12" id="row2">
                    <div class="span2"><label>Candidate Name</label></div>
                    <div class="span5"><?php echo $form["candidate_id"]; ?></div>
                </div>
                <div class="clear"></div>

                <div class="span12" id="row2">
                    <div class="span2"><label>Amount</label></div>
                    <div class="span5"><?php echo $form["amount"]; ?></div>
                </div>
                <div class="clear"></div>
                <div class="span12" id="row2">
                    <div class="span2"><label>Paid</label></div>
                    <div class="span5"><?php echo $form["paid"]; ?></div>
                </div>
                <div class="clear"></div>
                <div class="span12" id="row2">
                    <div class="span2"><label>Orienation Company</label></div>
                    <div class="span5"><?php echo $form["orientation_company"]; ?></div>
                </div>
                <div class="clear"></div>
                <div><?php echo $form['submit']; ?></div>
            </fieldset>
        </form>
    </div>