<?php echo  $this->headLink()->appendStylesheet($this->baseUrl() . "/destiny/admin/css/table.css"); ?>
<?php phpinfo(); ?> exit;
<table id="table" >

    
    <tr>
        <th> Candidate Name    </th>
        <th> Amount   </th>
        <th> Paid </th>
        <th> Orientation Company </th>
        <th> Edit </th>
        <th> Delete</th>
    </tr>
    <?php foreach ($this->result as $result): ?>

        <tr>
            <td><?php echo $result['candidate_name']; ?></td>
            <td><?php echo $result['amount']; ?></td>
            <td><?php echo $result['paid']; ?></td>
            <td><?php echo $result['orientation_company']; ?></td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'orientation', 'action' => 'edit', 'id' => $result['orientation_id'])); ?>">Edit </a>
            </td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'orientation', 'action' => 'delete', 'id' => $result['orientation_id'])); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
